# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

traverse <- function(l) {
    .Call('_mtest_traverse', PACKAGE = 'mtest', l)
}

sl <- function(from) {
    .Call('_mtest_sl', PACKAGE = 'mtest', from)
}

mpvals <- function(l, cutoff, rw = 1L, cl = 1L) {
    .Call('_mtest_mpvals', PACKAGE = 'mtest', l, cutoff, rw, cl)
}

mtest <- function(l, cutoff, rw = 1L, cl = 1L) {
    .Call('_mtest_mtest', PACKAGE = 'mtest', l, cutoff, rw, cl)
}

